# Generated by Django 4.2.3 on 2023-08-30 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_comment_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='new_field_debugging_example',
        ),
        migrations.RemoveField(
            model_name='post',
            name='second_new_field_debugging_example',
        ),
    ]
